### ISSUE TITLE
add VerifyConcatenate and IsStored atomic predicates

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/ovm-compiler#57]
## Description

* VerifyConcatenate(bytes, bytes_a, bytes_b) for confirmation signature.
* separate IsStored(root, block_number) and verifyInclusion(leaf, range, token, root, proof).

VerifyConcatenate verified bytes is concatenated of bytes_a and bytes_b.
IsStored verifies `root` is stored in `block_number`.

### Task List

* [x] add IsStored quantifier
* [x] add VerifyConcat quantifier
* [x] add Stored quantifier
* [x] add Concat quantifier
* [x] add Hash quantifier
* [x] fix swap example
